### ISSUE TITLE
[Bug]: Surgical bed does not output signals correctly in hosted games

### ISSUE THREAD

**Issue by MuzAgaci** [OlegBSTU/Neurotrauma#15]
### LuaForBarotrauma version

1.0.95

### Expansions in use

No expansions

### Neurotrauma Version

A1.9.5h3

### Reproduction steps

1. Load a hosted game
2. Wire any output to surgical bed to a terminal
3. Observe terminal that is wired to the bed
4. Surgical bed doesnt give out signals correctly

**Comment by dontmatterbro** [comment]
Fix for this is letting `surgerytable.lua` to run on client.

**Comment by OlegBSTU** [comment]
Thanks for reporting! Fixed in commit [https://github.com/OlegBSTU/Neurotrauma/commit/c094b4f036c1f200a0ba262572e7e2c0f9b7febe](url)
