### ISSUE TITLE
[Bug]: Adrenaline applies Adrenaline Rush without being consumed when used in any way except health menu

### ISSUE THREAD

**Issue by ThousandFields** [OlegBSTU/Neurotrauma#29]
### LuaForBarotrauma version

1.0.96

### Expansions in use

No expansions

### Neurotrauma Version

A1.9.6

### Reproduction steps

Method 1: Auto-injector Headset
1. Equip an auto-injector headset
2. Place adrenaline into the headset
3. take damage until under 50% vitality

Method 2: Swing item
1. Equip adrenaline in hand
2. Swing and inject another crewmate

**Comment by OlegBSTU** [comment]
Fixed in https://github.com/OlegBSTU/Neurotrauma/commit/bf6d1388b6ef7123ecc74ae2e769ab6aaa095397 . Thanks for reporting!
