### ISSUE TITLE
[Bug]: Medical starter crate duplicates items on save and quit and new rounds

### ISSUE THREAD

**Issue by ThousandFields** [OlegBSTU/Neurotrauma#9]
### LuaForBarotrauma version

1.0.93

### Expansions in use

No expansions

### Neurotrauma Version

A1.9.3h1

### Reproduction steps

1. Purchase a Medical starter crate from a merchant that sells it (either buy option works), or craft one
2. Place it on the ground in the submarine, in a shelf, or hold it
3. Save and quit or proceed to next round
4. New items will appear beside the Medical starter crate

The Medical starter crate will NOT duplicate items if:
1. The player is in singleplayer
2. The crate is on the ground or in a shelf
The Crate will still duplicate items in singleplayer if the player is holding it. The Crate will always duplicate items in multiplayer.

**Comment by OlegBSTU** [comment]
Fixed in commit 8ef9a7e427f129a5f340b71c8d88093be24e2b67 . Thanks for the report!
